### ISSUE TITLE
Testing structure causes false passing of tests

### ISSUE THREAD

**Issue by opotowsky** [cyclus/cymetric#74]
The cyclus simulations remain in the test directory and this caused all my tests to pass while others failed (when mine should have been failing). A simulation is run for multiple tests, but doesn't get deleted if the run of tests is successful. Changing this may require some significant changes to the testing architecture in cymetric.

**Comment by scopatz** [comment]
It should only be a one or two line change.

**Comment by scopatz** [comment]
`os.remove()`

**Comment by gidden** [comment]
It's more complicated than that. You have decorators over basic functions
and you `if file exists then continue`, I presume because you batch the
test functions (i.e., there are N tests per database). From my cursory
glance plus discussions with @elliottbiondo and @opotowsky, the only way to
fix this is to refactor grouped tests into test classes with setup/teardown
methods. You can still use decorators in that instance.

On Tue, May 12, 2015 at 5:48 PM, Anthony Scopatz <notifications@github.com>
wrote:

> os.remove()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cymetric/issues/74#issuecomment-101449333>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
Ok so it takes 4 - 5 lines.  Just change setup function in tests/tools.py to check whether it has been run in the current session or not.  Have a global boolean variable for this.  If it is false, remove all of the DBS files, if they exist.   Test classes are not needed. (I don't think that they are ever needed and almost always the wrong thing to use....in python testing, at least)

**Comment by gidden** [comment]
I do not disagree, but your suggestion is very conceptually complicated. I
suspect @opotowsky would like some example code, but I will let her request
it explicitly.

FWIW, I think test classes are a feature. I would interested in hearing why
you think they're almost always the wrong thing to use.

On Tue, May 12, 2015 at 6:13 PM, Anthony Scopatz <notifications@github.com>
wrote:

> Ok so it takes 4 - 5 lines. Just change setup function in tests/tools.py
> to check whether it has been run in the current session or not. Have a
> global boolean variable for this. If it is false, remove all of the DBS
> files, if they exist. Test classes are not needed. (I don't think that they
> are ever needed and almost always the wrong thing to use....in python
> testing, at least)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cymetric/issues/74#issuecomment-101456165>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by scopatz** [comment]
> FWIW, I think test classes are a feature. I would interested in hearing why
you think they're almost always the wrong thing to use.

1. most test classes come in the form of unittest, which is one of the most egregious violators of PEP8 in the standard library - and is almost a direct clone of JUnit.  The different needs of Python and Jave shine strongly here. (why do something in 10 lines, when you can do it in 2)

2. The purpose of a class (or type) in Python is to represent mutable state. This exactly what you don't want for testing - and particularly not unit tests.  These side effects can be completely mitigated by using functions since their closure provides a much stronger guarantee about the test code that is actually being run.

3. Any mutable state that you might need can be provided through various metaprogramming techniques such as decoration and mocking. I can't think of a use case that isn't covered by these two, especially if you allow for test generators (which are awesome, and not in unittest to the best of my knowledge).

Older code (pytables) is sort of given a pass because of when these tools became available. But new code really should avoid test classes completely.

**Comment by gidden** [comment]
Thank you for the explanation =)

On Tue, May 12, 2015 at 6:31 PM, Anthony Scopatz <notifications@github.com>
wrote:

> FWIW, I think test classes are a feature. I would interested in hearing why
> you think they're almost always the wrong thing to use.
>
>
>    1.
>
>    most test classes come in the form of unittest, which is one of the
>    most egregious violators of PEP8 in the standard library - and is almost a
>    direct clone of JUnit. The different needs of Python and Jave shine
>    strongly here. (why do something in 10 lines, when you can do it in 2)
>    2.
>
>    The purpose of a class (or type) in Python is to represent mutable
>    state. This exactly what you don't want for testing - and particularly not
>    unit tests. These side effects can be completely mitigated by using
>    functions since their closure provides a much stronger guarantee about the
>    test code that is actually being run.
>    3.
>
>    Any mutable state that you might need can be provided through various
>    metaprogramming techniques such as decoration and mocking. I can't think of
>    a use case that isn't covered by these two, especially if you allow for
>    test generators (which are awesome, and not in unittest to the best of my
>    knowledge).
>
> Older code (pytables) is sort of given a pass because of when these tools
> became available. But new code really should avoid test classes completely.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cymetric/issues/74#issuecomment-101459771>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192

**Comment by opotowsky** [comment]
@scopatz, I think I get most of what you're saying, but I do not know what you mean by 'run in the current session'. Other than that, I think I grasp this conceptually but @gidden is right; I might need a pointer to get me on the right path with respect to the code.

**Comment by scopatz** [comment]
In the current session means "this run of python,"  which here means "this run of the tests".  In tools.py add a global variable called something like `HAS_BEEN_RUN = False`  Then add something like the following lines to the top of the setup function.

```python
global HAS_BEEN_RUN
if not HAS_BEEN_RUN:
    HAS_BEEN_RUN = True
    for t, _, _, _ in DBS:
        os.remove(t)
```

**Comment by gidden** [comment]
FWIW this is a completely new design pattern for me

On Tue, May 12, 2015 at 7:17 PM, Anthony Scopatz <notifications@github.com>
wrote:

> In the current session means "this run of python," which here means "this
> run of the tests". In tools.py add a global variable called something like HAS_BEEN_RUN
> = False Then add something like the following lines to the top of the
> setup function.
>
> global HAS_BEEN_RUNif not HAS_BEEN_RUN:
>     HAS_BEEN_RUN = True
>     for t, _, _, _ in DBS:
>         os.remove(t)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cyclus/cymetric/issues/74#issuecomment-101465916>.
>



-- 
Matthew Gidden, Ph.D.
Postdoctoral Associate, Nuclear Engineering
The University of Wisconsin -- Madison
Ph. 225.892.3192
